# ワークフロー名(任意)
name: jestTest

# トリガーとなる GitHub イベント
on:
  # 対象ファイル(frontend/src/**)がpush時に起動
#  push:
#    paths:
#      - "frontend/src/**"

  # workflow_dispatchを指定しておくとGitHubのコンソールから実行可能になる
  workflow_dispatch:

# 使用するシェルと実行するディレクトリを指定
defaults:
  run:
    shell: bash
    working-directory: frontend

# ワークフローの実行処理
jobs:
  # ジョブ名(任意)
  test:
    # ジョブが実行されるランナー(仮想デバイス)の種類
    runs-on: ubuntu-latest
    # タイムアウトの時間を設定しておく
    timeout-minutes: 10

    # ジョブのステップ
    steps:
      # チェックアウト
      - uses: actions/checkout@v3

      # Nodeをセットアップ
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: "16"
    
      # npmをインストール
      - name: npmInstall
        run: npm install

      # npm testを実行    
      - name: jestTest
        run: npm test
